In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [4]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import h5py
warnings.resetwarnings()
warnings.simplefilter(action='ignore', category=ImportWarning)
warnings.simplefilter(action='ignore', category=RuntimeWarning)
warnings.simplefilter(action='ignore', category=DeprecationWarning)
warnings.simplefilter(action='ignore', category=ResourceWarning)

In [5]:
from keras.datasets import mnist

In [2]:
(train_data, train_labels), (test_data, test_labels) = mnist.load_data()

In [9]:
train_data.shape

(60000, 28, 28)

In [8]:
x=train_data

In [18]:
xm.shape

(100, 28, 28)

In [108]:
N=60000
M=100
alpha=0.01 #step size,        or 0.02, 0.1
D=28*28 #dimension of x_i 28*28
J=2   #dimension of z         or 5,10,20

#initialize \phi
u=np.zeros([10000,J])  #assume 10000 iterations, can kick out empty rows if converge early
sig2=np.zeros([10000,J])
u[0,]=np.random.normal(0,0.01,J)
sig2[0,]=np.random.normal(0,0.01,J)**2
#initialize \theta
uprime=np.zeros([10000,D])  #assume 10000 iterations, can kick out empty rows if converge early
sig2prime=np.zeros([10000,D])
uprime[0,]=np.random.normal(0,0.01,D)
sig2prime[0,]=np.random.normal(0,0.01,D)**2

#set seed
np.random.seed(123)
L=np.zeros([10000,M])        # we want to keep the track of lower bound each iter to replicate Fig2
LM=np.zeros(10000)           #LM with batch size M, for 10000 iter
#maybe we can get rid of Ls if the code is slow and only keep the SGVB update

In [31]:
u=np.zeros([10000,J])
u[0,]=np.random.normal(0,0.01,J)
u[0,]

array([ 0.00282978, -0.01506295])

In [23]:
np.random.multivariate_normal(np.zeros(J),np.eye(2))

array([-1.0856306 ,  0.99734545])

In [35]:
sig2[0,]*np.random.multivariate_normal(np.zeros(J),np.eye(2))

array([ 0.02634477, -0.00427774])

In [48]:
sig2[i,]

array([8.00768304e-06, 2.26892377e-04])

In [49]:
np.log(sig2[i,])

array([-11.7351091 ,  -8.39103477])

In [50]:
i=0
sum(np.log(sig2[i,]))

-20.126143862822957

In [51]:
sig2prime[i,]**(-1)

array([3.18640852e+03, 2.04153235e+04, 1.16253850e+04, 3.31682106e+05,
       1.23468416e+09, 2.11126136e+04, 1.29268414e+04, 1.24309370e+05,
       1.54174610e+04, 3.35026122e+03, 6.54438917e+04, 3.03717655e+04,
       8.72276515e+04, 7.14486793e+07, 1.74720966e+03, 5.86522469e+04,
       1.04392397e+04, 1.99629264e+03, 5.97137268e+03, 9.26714538e+03,
       3.28889778e+03, 1.57009502e+04, 1.13495248e+07, 8.74556545e+03,
       1.26046521e+04, 3.24714806e+03, 4.47036984e+03, 8.74431098e+03])

In [56]:
xm[i,].shape

(28, 28)

In [55]:
((xm[i,]-uprime[i,])**2).shape#*sig2prime[i,]**(-1)

(28, 28)

In [72]:
u_temp=np.random.normal(0,0.01,[M,J])
sig2_temp=np.random.normal(0,0.01,[M,J])**2
sum(u_temp[:,1])
eps=np.random.multivariate_normal(np.zeros(J),np.eye(2))
u_temp[i,]+sig2_temp[i,]*eps
sum(u_temp[i,])
sum(1/sig2_temp[:,1]-1)

320537132.2139021

In [109]:
u_temp=np.random.normal(0,0.01,[M,J])
sig2_temp=np.random.normal(0,0.01,[M,J])**2
uprime_temp=np.random.normal(0,0.01,[M,D])
sig2prime_temp=np.random.normal(0,0.01,[M,D])**2

In [110]:
uprime_temp.shape

(100, 784)

In [92]:
d=1
sum(1/sig2prime_temp[:,d]*(xmresp[:,d]-uprime_temp[:,d]))

-517454.81495356164

In [94]:
(1/sig2prime_temp[:,d]*(xmresp[:,d]-uprime_temp[:,d])).shape

(100,)

In [87]:
xm.reshape(100,-1).shape

(100, 784)

In [85]:
xm[i,].reshape(-1,1).shape

(784, 1)

In [96]:
D*np.log(2*np.pi)

51.46055785946167

In [91]:
xmresp=xm.reshape(M,-1) 

In [99]:
t=0

In [101]:
1/2 * (1+sum(np.log(sig2_temp[i,]))-sum(u_temp[i,])-sum(sig2_temp[i,])) - 1/2* (D*np.log(2*np.pi)+sum(np.log(sig2prime_temp[i,])))

109.62274446344071

In [111]:
uprime_temp[i,].shape

(784,)

In [112]:
- 1/2 * sum((xmresp[i,]-uprime_temp[i,])**2*1/sig2prime_temp[i,])

-36849881184799.125

In [121]:
j=1
alpha*N/M*(-sum(u_temp[:,j]))
alpha*N/M*(1/2)*sum(1/sig2_temp[:,j]-1)
alpha*N/M*sum(1/sig2prime_temp[:,d]*(xmresp[:,d]-uprime_temp[:,d]))
alpha*N/M*sum(1/2 * (1/sig2prime_temp[:,d]*((xmresp[:,d]-uprime_temp[:,d])**2-1)))

-858043966.4906757

In [122]:
if (2>1)&(1>0):
    print(0)

0


In [17]:
#repeat until converge
t=0
xm=x[np.random.randint(0,N-1,M),]
xmresp=xm.reshape(M,-1)      #reshape the xi from matrix 28*28 to a row vector 1*784
u_temp=np.random.normal(0,0.01,[M,J])
sig2_temp=np.random.normal(0,0.01,[M,J])**2
uprime_temp=np.random.normal(0,0.01,[M,D])
sig2prime_temp=np.random.normal(0,0.01,[M,D])**2

for i in range(M):
    # MLP use x_i to get \phi_t(i) u_temp[i,] and sig2_temp[i,], which is same dimension as z (J)
    eps=np.random.multivariate_normal(np.zeros(J),np.eye(2))
    z=u_temp[i,]+sig2_temp[i,]*eps
    # MLP use z_i to get \theta_t(i) uprime_temp[i,] and sig2prime_temp[i,], which is same dimension as x(D)
    L[t,i]=1/2 * (1+sum(np.log(sig2_temp[i,]))-sum(u_temp[i,])-sum(sig2_temp[i,])) - 1/2* (D*np.log(2*np.pi)+sum(np.log(sig2prime_temp[i,])))- 1/2 * sum((xmresp[i,]-uprime_temp[i,])**2*1/sig2prime_temp[i,])
LM[t]=N/M*sum(L[t,])
for j in range(J):
    u[t+1,j]=u[t,j]- alpha*N/M*(-sum(u_temp[:,j]))    # to confirm it's minus?? gradient descent. the written part says ascent
    sig2[t+1,j]=sig2[t,j] -alpha*N/M*(1/2)*sum(1/sig2_temp[:,j]-1)
for d in range(D):
    uprime[t+1,d]=uprime[t,d]-alpha*N/M*sum(1/sig2prime_temp[:,d]*(xmresp[:,d]-uprime_temp[:,d]))
    sig2prime[t+1,d]=sig2prime[t,d]-alpha*N/M*sum(1/2 * (1/sig2prime_temp[:,d]*((xmresp[:,d]-uprime_temp[:,d])**2-1)))

In [17]:
while True:
    t=0
    xm=x[np.random.randint(0,N-1,M),]
    xmresp=xm.reshape(M,-1)      #reshape the xi from matrix 28*28 to a row vector 1*784
    u_temp=np.random.normal(0,0.01,[M,J])
    sig2_temp=np.random.normal(0,0.01,[M,J])**2
    uprime_temp=np.random.normal(0,0.01,[M,D])
    sig2prime_temp=np.random.normal(0,0.01,[M,D])**2
    
    for i in range(M):
        # MLP use x_i to get \phi_t(i) u_temp[i,] and sig2_temp[i,], which is same dimension as z (J)
        eps=np.random.multivariate_normal(np.zeros(J),np.eye(2))
        z=u_temp[i,]+sig2_temp[i,]*eps
        # MLP use z_i to get \theta_t(i) uprime_temp[i,] and sig2prime_temp[i,], which is same dimension as x(D)
        L[t,i]=1/2 * (1+sum(np.log(sig2_temp[i,]))-sum(u_temp[i,])-sum(sig2_temp[i,])) - 1/2* (D*np.log(2*np.pi)+sum(np.log(sig2prime_temp[i,])))- 1/2 * sum((xmresp[i,]-uprime_temp[i,])**2*1/sig2prime_temp[i,])
        LM[t]=N/M*sum(L[t,])
        
    for j in range(J):
        u[t+1,j]=u[t,j]- alpha*N/M*(-sum(u_temp[:,j]))    # to confirm it's minus?? gradient descent. the written part says ascent
        sig2[t+1,j]=sig2[t,j] -alpha*N/M*(1/2)*sum(1/sig2_temp[:,j]-1)
    
    for d in range(D):
        uprime[t+1,d]=uprime[t,d]-alpha*N/M*sum(1/sig2prime_temp[:,d]*(xmresp[:,d]-uprime_temp[:,d]))
        sig2prime[t+1,d]=sig2prime[t,d]-alpha*N/M*sum(1/2 * (1/sig2prime_temp[:,d]*((xmresp[:,d]-uprime_temp[:,d])**2-1)))
        
    if (np.norm(u[t+1,]-u[t,])<1e-6) & (np.norm(sig2[t+1,]-sig2[t,])<1e-6) & (np.norm(uprime[t+1,]-uprime[t,])<1e-6) & (np.norm(sig2prime[t+1,]-sig2prime[t,])<1e-6):
        break
    
    t=t+1